version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Map port 5173 on the host to port 5173 in the container
    restart: always
